framework:
    # https://symfony.com/doc/current/reference/configuration/framework.html#cache-1
    cache:
        app: cache.adapter.filesystem
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
                public: false
            doctrine.system_cache_pool:
                adapter: cache.system
                public: false
            cache.cloudfront_signed_urls:
                adapter: cache.adapter.system
            cache.cloudsearch_suggestions:
                adapter: cache.adapter.system

when@dev:
    framework:
        cache:
            app: cache.adapter.array
            system: cache.adapter.array
