doctrine:
    dbal:
        driver: pdo_mysql
        server_version: '8.0.43'
        host: '%env(DATABASE_HOST)%'
        port: 3306
        dbname: '%env(DATABASE_NAME)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collation: utf8mb4_general_ci
        mapping_types:
            enum: string
        logging: '%kernel.debug%'
        profiling: '%kernel.debug%'
        profiling_collect_backtrace: '%kernel.debug%'
        profiling_collect_schema_errors: '%kernel.debug%'
        keep_replica: false
        options:
            3: 2 # this option tells PDO to throw exceptions for errors, which is generally recommended for better error handling
            20: false # this disables emulation mode for prepared statements, which can improve security and performance
            1003: true # this enables compression in client/server protocol
    orm:
        default_entity_manager: default
        enable_native_lazy_objects: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        quote_strategy: doctrine.orm.quote_strategy.default
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool
        auto_mapping: true
        controller_resolver:
            auto_mapping: false
        mappings:
            App:
                mapping: true
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
